web: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
worker: python -m celery -A app.core.celery_app.celery_app worker --loglevel=info
beat: python -m celery -A app.core.celery_app.celery_app beat --loglevel=info